---
title: "Report"
author: "sophia"
date: "29 3 2021"
output: html_document
---

```{r load-packages, include=FALSE}
library(dplyr)
library(magrittr)
library(knitr)
library(tidyquant)
library(bizdays)
library(tidyverse)
library(readxl)
library(rmarkdown)

"%!in%" <- function(x,y)!('%in%'(x,y))
```

```{r code, include = FALSE}
### look at djia index

## add BM simulation after today
## compare to climate policy introduction dates

#--------------------------------------------------------------------

### djia index data

# get daily djia ticker from yahoo finance
djia <- tq_get("DJIA", get = "stock.prices", from = "1990-01-01")

# calculate returns
djia <- djia %>%
  tq_mutate(select = adjusted,
    mutate_fun = periodReturn,
    period = "daily",
    type = "arithmetic")  %>%
  mutate(date = ymd(date))

### simulation

# simulation parameters
s0 <- tail(djia$adjusted, 1) # initial stock price for simulation
dt <- 1 # time step
sim_range <- tibble("sim_range" = seq(ymd(tail(djia$date, 1)),
  ymd("2030-12-31"), by = "1 day")) %>%
  filter(!wday(sim_range) %in% c(1, 7)) %>%
  slice(-1)  # prediction horizon
sim_length <- nrow(sim_range) # length of prediction horizon
time_position <- 1:sim_length # position in time as delta to last data point
sim_steps <- sim_length / dt # number of time points in prediction horizon
mu <- 0.000001 # alternatively: mean of djia$daily.returns
sig <- 0.003 # alternatively: sd of djia$daily.returns
nsim <- 10

# create random value matrix
ret_sim <- matrix(rnorm(n = nsim * sim_steps, mean = 0, sd = 1),
  nsim, sim_steps) %>%
  apply(1, cumsum) %>%
  t()
# set drift and diffusion
my_drift <- matrix((mu - 0.5 * sig**2) * time_position)
my_diffusion <- sig * ret_sim
# combine drift diffusion and random value according to GBM modl
my_stock <- apply(my_diffusion, 1,
  function(x, drift) s0 * exp(x + drift), drift = my_drift)

## combine simulation and index data
total_stock_data <- tibble(
  "date" = append(djia$date, sim_range$sim_range),
  "dow_historic" = c(djia$adjusted, rep(NA, length(sim_range$sim_range))),
  ) %>%
  cbind(
      rbind(matrix(data = NA, nrow = length(djia$adjusted), ncol = nsim),
      my_stock) %>%
      as_tibble(.name_repair = c("unique", "minimal", "universal"))
    )
```

```{r plot}
total_stock_data  %>%
  gather(key = "dow_series", value = "value", -date)  %>%
  ggplot(aes(x = date, y = value)) +
  geom_path() +
  theme_classic()
```

```{r code, include = FALSE}
### US policy/law events: climate policy database

# import carbon policy decision dates
carbon_policy <- read_excel(path = "data/climate_policies.xlsx")
carbon_policy <- carbon_policy  %>% select(-"Date_Source")

# create vector of decision dates
decision_dates <- unique(carbon_policy$Signation_Date) %>%
  na.omit() %>%
  ymd()
```

```{r plot}

# plot with all data + simulation
total_stock_data  %>%
  gather(key = "dow_series", value = "value", -date)  %>%
  ggplot(aes(x = date, y = value)) +
  geom_path() +
  geom_rect(data = total_stock_data %>%
      filter(date %in% decision_dates)  %>%
      gather(key = "dow_series", value = "value", -date),
    aes(xmin = (date - 10), xmax = (date + 10), ymin = -Inf, ymax = Inf),
    fill = "orange", alpha = 0.05) +
  theme_classic()

# zoom in plot
total_stock_data  %>%
  gather(key = "dow_series", value = "value", -date)  %>%
  filter(date >= min(decision_dates) - 200 &
    date <= max(decision_dates) + 200)  %>%
  ggplot(aes(x = date, y = value)) +
  geom_path() +
  geom_rect(data = total_stock_data %>%
      filter(date >= min(decision_dates) - 200 &
        date <= max(decision_dates) + 200)  %>%
      filter(date %in% decision_dates)  %>%
      gather(key = "dow_series", value = "value", -date),
    aes(xmin = (date - 10), xmax = (date + 10), ymin = -Inf, ymax = Inf),
    fill = "orange", alpha = 0.05) +
  theme_classic()

# compare average daily return at the decision day
djia  %>%
  select(date, daily.returns)  %>%
  mutate(in_decision_dates = date %in% decision_dates)  %>%
  group_by(in_decision_dates)  %>%
  summarise(return_mean = mean(daily.returns),
    return_variance = var(daily.returns))

# create a tibble which contains dates and policy names (merge downstream)
carbon_policy_event <- carbon_policy  %>%
  mutate(date = Signation_Date)  %>%
  select(date, Policy_Name)  %>%
  unique()

# show returns on the decision day with name of event
djia  %>%
  select(date, daily.returns)  %>%
  filter(date %in% decision_dates)  %>%
  inner_join(carbon_policy_event)
```

```{r code, include = FALSE}
  
### add worldwide policy events: MSCI

# import data
carbon_policy_world <- read_excel(path = "data/climate_policies2.xlsx")

# create highlight tibbles
# for US policy events
highlights1 <- carbon_policy  %>%
  mutate(date = Signation_Date)  %>%
  inner_join(djia)  %>%
  mutate(date = ymd(date), policy_name = Policy_Name)  %>%
  select(date, policy_name, adjusted, daily.returns)  %>%
  unique()

# for world policy events
highlights2 <- carbon_policy_world  %>%
  inner_join(djia)  %>%
  mutate(date = ymd(date))  %>% 
  select(date, policy_name, impact, adjusted, daily.returns)

# plot djia with all events
djia  %>%
  select(adjusted, date)  %>%
  ggplot(aes(x = date, y = adjusted)) +
  geom_line() +
  geom_rect(data = highlights2  %>% filter(impact == "progress"),
    aes(xmin = (date - 30), xmax = (date + 30), ymin = -Inf, ymax = Inf),
    fill = "green", alpha = 0.2) +
  geom_rect(data = highlights2  %>% filter(impact == "setback"),
    aes(xmin = (date - 30), xmax = (date + 30), ymin = -Inf, ymax = Inf),
    fill = "orange", alpha = 0.2) +
  geom_rect(data = highlights1,
    aes(xmin = (date - 30), xmax = (date + 30), ymin = -Inf, ymax = Inf),
    fill = "yellow", alpha = 0.2) +
  theme_classic()

# compare average daily return on all decision dates
djia  %>%
  select(date, daily.returns)  %>%
  mutate(in_decision_dates = date %in% highlights1$date |
    date %in% highlights2$date)  %>%
  group_by(in_decision_dates)  %>%
  summarise(return_mean = mean(daily.returns),
    return_variance = var(daily.returns))

# show returns on the decision day with name of event
djia  %>%
  select(date, daily.returns)  %>%
  filter(date %in% decision_dates)  %>%
  inner_join(carbon_policy_event)
```



